// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $characters_id_ from "./routes/characters/[id].tsx";
import * as $favorites from "./routes/favorites.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $CharacterCard from "./islands/CharacterCard.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ShowCookie from "./islands/ShowCookie.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/characters/[id].tsx": $characters_id_,
    "./routes/favorites.tsx": $favorites,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharacterCard.tsx": $CharacterCard,
    "./islands/Counter.tsx": $Counter,
    "./islands/ShowCookie.tsx": $ShowCookie,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
